name: pdfLaTeX compile the homework questions

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    if: github.event.repository.html_url == 'https://github.com/BrownCSCI1430/Homework1_ImageFiltering_Template'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Enable Page Export
        run: sed -i 's/\\documentclass{csci1430}/\\documentclass[exportexpectedpages]{csci1430}/' questions/Homework1_Questions_Template.tex

      - name: Generate Page Map (Compile 1)
        uses: dante-ev/latex-action@2025-A
        with:
          root_file: Homework1_Questions_Template.tex
          working_directory: questions
          compiler: pdflatex
          args: -interaction=nonstopmode

      - name: Disable Page Export
        run: sed -i 's/\\documentclass[exportexpectedpages]{csci1430}/\\documentclass{csci1430}/' questions/Homework1_Questions_Template.tex

      - name: Generate Final PDF (Compile 2)
        uses: dante-ev/latex-action@2025-A
        with:
          root_file: Homework1_Questions_Template.tex
          working_directory: questions
          compiler: latexmk
          args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode

      - name: Commit and Push
        run: |
          git add questions/Homework1_Questions_Template.pdf questions/csci1430_expectedpages.tex
          git config --local user.name 'github-actions-bot'
          git config --local user.email 'cs1430-github-actions[bot]@users.noreply.github.com'
          git commit -m "Compile written PDF and update page map [skip ci]" || echo "No changes to commit"
          git push
